version: '3'
services:
  mysql-standalone:
    image: 'mysql:5.7'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=schooldb
    ports:
      - "3307:3306"
  springboot-docker-container:
    image: springboot-docker-container
    ports:
      - "8090:8090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-standalone:3306/schooldb?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
    build:
      context: "./back_end_api"
      dockerfile: "Dockerfile"
    depends_on:
      - mysql-standalone
  react-ui:
    build: 
      dockerfile: "Dockerfile"
      context: "./front_end"
    ports:
      - "3000:3000"
    volumes:
      - '/app/node_modules'
      - './front_end:/app'
    container_name: react-ui
    stdin_open: true
