version: "3"
services:
  server:
    image: backend
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/schooldb?useSSL=false
    networks:
      - springmysql-net
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:5.7
    networks:
      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=hassan
      - MYSQL_DATABASE=schooldb
      - MYSQL_USER=hassan
      - MYSQL_PASSWORD=hassan

networks:
  springmysql-net: